spring.application.name=gameReunion
spring.datasource.url=jdbc:mysql://localhost:3306/gamereunion
spring.datasource.username=root
spring.datasource.password=RayaC0ca22
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.web-application-type=servlet