spring.application.name=gameReunion
spring.datasource.url=jdbc:mysql://mysql-222bc616-gamegroup.h.aivencloud.com:10273/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_UgWccFjxOym_ijzITO7
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.web-application-type=servlet